server:
  port: 80
spring:
  thymeleaf:
    cache: false


#  security:
#    user:
#      name: admin
#      password: 123
#      roles: admin



liyiruo:
  security:
    authention:
      loginPage: /login/page #登录页面
      loginProcessingUrl: /login/form #登录表单提交URL
      usernameParameter: name #登录表单的用户名属性
      passwordParameter: pwd #登录表单的用户名属性
      staticPaths:
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT  # 认证之后 响应的类型:JSON/REDIRECT
