server:
  port: 80
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jdbc?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: '!QAZ2wsx'
    driver-class-name: com.mysql.cj.jdbc.Driver


#  security:
#    user:
#      name: admin
#      password: 123
#      roles: admin



liyiruo:
  security:
    authention:
      loginPage: /login/page #登录页面
      loginProcessingUrl: /login/form #登录表单提交URL
      usernameParameter: name #登录表单的用户名属性
      passwordParameter: pwd #登录表单的用户名属性
      imageCodeUrl: /code/image
      mobileCodeUrl: /code/mobile
      mobilePage: /mobile/page
      tokenValiditySeconds: 604800
      staticPaths:
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT  # 认证之后 响应的类型:JSON/REDIRECT
